stages:
  - lint
  - tests
  - build

push-image-to-registry:
  stage: build
  tags:
    - docker
  services:
    - docker:dind
  image: docker
  inherit:
    default: false
  script:
    - echo "---------- install git ----------"
    - apk update
    - apk add git

    - echo "---------- Cloning the repository ----------"
    - git clone https://airflow-docker:$ACCESS_DOCKER_DAGS@gitlab.com/lappis-unb/decidimbr/servicos-de-dados/airflow-docker.git

    - ls
    - pwd
    - echo "---------- Copying files to build the image ----------"

    - mv airflow-docker/Dockerfile .
    - mkdir airflow-dags
    - mv airflow-docker/requirements.txt ./airflow-dags/.

    - ls
    - pwd

    - echo "---------- Updating the Dockerfile ----------"
    - echo "COPY ./dags ./dags" >> Dockerfile
    - echo "COPY ./plugins ./dags" >> Dockerfile

    - echo "--------- Building the image ----------"
    - docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

default:
  image: python:3.10-slim
  retry: 0
  before_script:
    - pip install -r requirements.txt # Install dependencies
    - pip install -r requirements.testing.txt # Install testing dependencies

