
MD004: false

# MD007 ul-indent - Unordered list indentation
MD007: false

# MD013 line-length - Line length
MD013: false

# MD026 no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# MD029 ol-prefix - Ordered list item prefix
MD029: false

# MD030 list-marker-space - Spaces after list markers
MD030: false

# MD033 no-inline-html - Inline HTML
MD033: false

# MD036 no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false
